# Generated by Django 3.1.8 on 2021-04-26 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intentions_page', '0002_auto_20210426_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intention',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='intention',
            name='created_datetime',
        ),
    ]
