# Generated by Django 3.1.8 on 2021-04-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions_page', '0004_auto_20210426_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intention',
            name='title',
            field=models.CharField(max_length=500),
        ),
    ]
