# Generated by Django 3.1.8 on 2021-05-11 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import intentions_page.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intentions_page', '0005_auto_20210427_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intention',
            name='date',
            field=models.DateField(default=intentions_page.models.get_working_day_date),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(default=intentions_page.models.get_working_day_date)),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
