# Generated by Django 3.1.8 on 2021-05-11 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions_page', '0006_auto_20210511_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='note',
            constraint=models.UniqueConstraint(fields=('date', 'creator'), name='One note per user per day'),
        ),
    ]
