# Generated by Django 3.1.8 on 2021-05-13 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intentions_page', '0007_auto_20210511_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-created_datetime']},
        ),
    ]
