# Generated by Django 3.1.8 on 2021-07-29 14:26

from django.db import migrations, models
import intentions_page.models


class Migration(migrations.Migration):

    dependencies = [
        ('intentions_page', '0008_auto_20210513_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentionsDraft',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateField(default=intentions_page.models.get_working_day_date)),
            ],
        ),
    ]
