# Generated by Django 3.1.8 on 2021-07-29 14:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intentions_page', '0009_intentionsdraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentionsdraft',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
