# Generated by Django 3.1.8 on 2021-07-29 14:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('intentions_page', '0010_intentionsdraft_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='intentionsdraft',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='intentionsdraft',
            name='version',
            field=models.IntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='intentionsdraft',
            constraint=models.UniqueConstraint(fields=('date', 'creator'), name='One intentions draft per user per day'),
        ),
    ]
