# Generated by Django 3.1.8 on 2021-08-16 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intentions_page', '0011_auto_20210729_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intention',
            options={'ordering': ['created_datetime']},
        ),
    ]
